name: Publish shipping-components

on:
  push:
    branches:
      - main
    paths:
      - "packages/shipping-components/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@nadineouro"

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build --workspace=packages/shipping-components

      - name: Publish to GitHub Packages
        run: npm publish --workspace=packages/shipping-components --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
